import { jsPDF } from "jspdf";
import { formatKsh } from "./currency";

const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];

export interface ReceiptData {
  receiptNumber: string;
  issueDate: string; // YYYY-MM-DD
  landlord: { name?: string | null; email?: string | null };
  tenant: { name: string; email?: string | null; phone?: string | null; unit?: string | null };
  property?: { name?: string | null; address?: string | null } | null;
  payment: {
    period_month: number;
    period_year: number;
    amount_due: number;
    amount_paid: number;
    paid_date?: string | null;
    due_date: string;
    method?: string | null;
    reference?: string | null;
    status: string;
    notes?: string | null;
  };
}

export function downloadReceiptPdf(data: ReceiptData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  // Header band
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Flashrentsolution", margin, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Rent Payment Receipt", margin, 70);

  doc.setFontSize(10);
  doc.text(`Receipt #: ${data.receiptNumber}`, pageW - margin, 50, { align: "right" });
  doc.text(`Issued: ${data.issueDate}`, pageW - margin, 65, { align: "right" });

  doc.setTextColor(15, 23, 42);
  y = 130;

  // Parties
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Landlord", margin, y);
  doc.text("Tenant", pageW / 2, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y += 16;
  doc.text(data.landlord.name || data.landlord.email || "—", margin, y);
  doc.text(data.tenant.name, pageW / 2, y);
  y += 14;
  if (data.landlord.email) doc.text(data.landlord.email, margin, y);
  const tenantContact = [data.tenant.email, data.tenant.phone].filter(Boolean).join(" · ");
  if (tenantContact) doc.text(tenantContact, pageW / 2, y);
  y += 24;

  // Property
  if (data.property?.name || data.property?.address) {
    doc.setFont("helvetica", "bold");
    doc.text("Property", margin, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    if (data.property?.name) { doc.text(data.property.name, margin, y); y += 12; }
    if (data.property?.address) { doc.text(data.property.address, margin, y); y += 12; }
    if (data.tenant.unit) { doc.text(`Unit: ${data.tenant.unit}`, margin, y); y += 12; }
    y += 10;
  }

  // Period title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(`Rent for ${months[data.payment.period_month - 1]} ${data.payment.period_year}`, margin, y);
  y += 18;

  // Table-ish rows
  const rows: [string, string][] = [
    ["Amount due", formatKsh(data.payment.amount_due)],
    ["Amount paid", formatKsh(data.payment.amount_paid)],
    ["Balance", formatKsh(Math.max(0, Number(data.payment.amount_due) - Number(data.payment.amount_paid)))],
    ["Due date", data.payment.due_date],
    ["Paid date", data.payment.paid_date || "—"],
    ["Method", data.payment.method || "—"],
    ["Reference", data.payment.reference || "—"],
    ["Status", data.payment.status.toUpperCase()],
  ];

  doc.setFontSize(10);
  doc.setDrawColor(226, 232, 240);
  rows.forEach(([k, v]) => {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(k, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(String(v), pageW - margin, y, { align: "right" });
    y += 8;
    doc.line(margin, y, pageW - margin, y);
    y += 14;
  });

  if (data.payment.notes) {
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Notes", margin, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(data.payment.notes, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 12;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "This receipt is generated by Flashrentsolution. Keep it for your records.",
    pageW / 2,
    doc.internal.pageSize.getHeight() - 30,
    { align: "center" }
  );

  doc.save(`receipt-${data.receiptNumber}.pdf`);
}
